src/objects/EECRM_Project__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>e-Commerce</fullName>
                </value>
                <value>
                    <fullName>Medicine</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Chemical</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Public Health</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
                <value>
                    <fullName>Teleworking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Checksum__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Checksum</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EECRM ProjectS</relationshipLabel>
        <relationshipName>EECRM_ProjectS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EECRM Project</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>EECRM Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EECRM ProjectS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EECRM_Projects.cls
public class EECRM_Projects extends fflib_SObjectDomain {
    public EECRM_Projects(List<EECRM_Project__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new EECRM_Projects(sObjectList);
        }
    }

    public override void onApplyDefaults(){
        
    }

    public override void onBeforeInsert(){
        assigneDefaultResponsiblePerson();
        calculateChecksum();
    }

    public override void onValidate(){
        validateProjectName();
    } 

    private void assigneDefaultResponsiblePerson(){
        for(SObject currentRecord : Records){
            if(currentRecord.get('Responsible_Person__c') == null){
                currentRecord.put('Responsible_Person__c',getDefaultResponsiblePerson().ID);
            }     
        }    
    } 

    private void validateProjectName(){
        Map<String,sObject> projects = new Map<String,sObject>();
        for(SObject currentRecord : Records){
            String projectName = (String) currentRecord.get('Project_Name__c');

            if(String.isBlank(projectName)){
                currentRecord.addError('Project Name is empty. Please fill it.');
            }           
            if(projects.containsKey(projectName)){
                currentRecord.addError('You are trying to duplicate projects names.');
            }else{
                projects.put(projectName,currentRecord);
            }   
        }

        List<sObject> duplicatedProjects = EECRM_SRV_ProjectsService.getInstance().getProjectsByNames(projects.keySet()); 
        System.debug(duplicatedProjects);       
        if(!projects.isEmpty()){
            for(sObject duplicatedProject : duplicatedProjects){
                String key = (String) duplicatedProject.get('Project_Name__c');
                if(projects.containsKey(key) && projects.get(key).ID != duplicatedProject.ID){
                    projects.get(key).addError('Duplicated Project Name : '+key); 
                }
            }            
        }
    } 

    private void calculateChecksum(){
        for(SObject currentRecord : Records){
            String hashTarget = buildHashTarget(currentRecord);            
            String hashBase64SHA1 = EECRM_UTL_Utils.generateHashBase64SHA1(hashTarget);
            currentRecord.put('Checksum__c',hashBase64SHA1);
        }   
    }
 
    private String buildHashTarget(SObject record){
        String category = (String) record.get('Category__c');      
        return EECRM_UTL_Utils.sortMultiPiclistAlphabetically(category) 
            + '' + record.get('Project_Name__c');
    }   

    private Contact getDefaultResponsiblePerson(){
        List<Contact> globalManager = [SELECT Id,UniqueId__c FROM Contact WHERE Global_Manager__c = true LIMIT 1];
        if(globalManager.isEmpty()){
            return new Contact();
        }else{
            return globalManager[0];
        }
        
    } 
}